# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'@export
OnlineSimulation <- function(Rm, Rlearner_ctr, Rlearner_wr, is_click, is_win, bid_t, clk_t, is_continue = FALSE) {
    .Call('IPinYouExp_OnlineSimulation', PACKAGE = 'IPinYouExp', Rm, Rlearner_ctr, Rlearner_wr, is_click, is_win, bid_t, clk_t, is_continue)
}

#'@export
OnlineSimulation2 <- function(Rm, Rlearner_wr, ECVR, is_win, bid_t, is_continue = FALSE) {
    .Call('IPinYouExp_OnlineSimulation2', PACKAGE = 'IPinYouExp', Rm, Rlearner_wr, ECVR, is_win, bid_t, is_continue)
}

